// Generated by CoffeeScript 1.3.3
(function() {
  var binaryXHR, stlParser;

  stlParser = require('./stl_parser');

  binaryXHR = require('binary-xhr');

  this.loadGeometry = function(location, callback) {
    if (typeof location === 'string') {
      return binaryXHR(location, function(error, data) {
        var geometry;
        if (error) {
          callback(error);
        }
        geometry = stlParser.parse(data);
        return callback(null, geometry);
      });
    } else {
      throw new Error("Dunno how to load geometry with location " + location + " (" + (typeof location) + ")");
    }
  };

  this.voxelateLayer = function(geometry, pos, scale, y) {};

}).call(this);
